// lib/schema.ts
// Database schema definitions for the skills system
// Note: This project uses raw SQL with postgres.js (Supabase), not an ORM
// These type definitions document the table structure

/**
 * skills table - Master list of all supported skills for filtering
 *
 * CREATE TABLE skills (
 *   slug TEXT PRIMARY KEY,
 *   display_name TEXT NOT NULL,
 *   category TEXT NOT NULL,
 *   match_languages TEXT[] NOT NULL DEFAULT '{}',
 *   match_topics TEXT[] NOT NULL DEFAULT '{}',
 *   match_keywords TEXT[] NOT NULL DEFAULT '{}',
 *   created_at TIMESTAMP NOT NULL DEFAULT NOW()
 * );
 */
export interface Skill {
  slug: string;
  displayName: string;
  category: string;
  matchLanguages: string[];
  matchTopics: string[];
  matchKeywords: string[];
  createdAt: Date;
}

/**
 * user_skill_scores table - Computed scores linking users to skills
 *
 * CREATE TABLE user_skill_scores (
 *   username TEXT NOT NULL REFERENCES leaderboard(username) ON DELETE CASCADE,
 *   skill_slug TEXT NOT NULL REFERENCES skills(slug) ON DELETE CASCADE,
 *   score REAL NOT NULL DEFAULT 0,
 *   repo_count INTEGER NOT NULL DEFAULT 0,
 *   top_repos_json JSONB,
 *   computed_at TIMESTAMP NOT NULL DEFAULT NOW(),
 *   PRIMARY KEY (username, skill_slug)
 * );
 *
 * CREATE INDEX idx_uss_skill ON user_skill_scores(skill_slug);
 * CREATE INDEX idx_uss_score ON user_skill_scores(score);
 * CREATE INDEX idx_uss_username ON user_skill_scores(username);
 */
export interface UserSkillScore {
  username: string;
  skillSlug: string;
  score: number;
  repoCount: number;
  topReposJson: TopRepoEntry[] | null;
  computedAt: Date;
}

/**
 * Structure of entries in top_repos_json
 */
export interface TopRepoEntry {
  fullName: string;
  ownerLogin: string;
  name: string;
  userPRs: number;
  stars: number;
  language: string | null;
  topics: string[];
  score: number;
}

/**
 * Skill categories for organization
 */
export type SkillCategory =
  | 'language' // Programming languages (TypeScript, Python, Go, etc.)
  | 'framework' // Frameworks (React, Next.js, Django, etc.)
  | 'platform' // Platforms (AWS, Docker, Kubernetes, etc.)
  | 'domain' // Domains (blockchain, ai, security, etc.)
  | 'tool'; // Tools (Git, CI/CD, etc.)

/**
 * Initial seed data for skills table
 * When adding a new skill, just add a row here and rerun the scoring
 */
export const SEED_SKILLS: Omit<Skill, 'createdAt'>[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // PROGRAMMING LANGUAGES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'typescript',
    displayName: 'TypeScript',
    category: 'language',
    matchLanguages: ['TypeScript'],
    matchTopics: ['typescript', 'ts'],
    matchKeywords: ['typescript', '.ts', '.tsx'],
  },
  {
    slug: 'javascript',
    displayName: 'JavaScript',
    category: 'language',
    matchLanguages: ['JavaScript'],
    matchTopics: ['javascript', 'js', 'nodejs', 'node', 'ecmascript'],
    matchKeywords: ['javascript', '.js', '.jsx', 'ecmascript'],
  },
  {
    slug: 'python',
    displayName: 'Python',
    category: 'language',
    matchLanguages: ['Python'],
    matchTopics: ['python', 'python3', 'py', 'django', 'flask', 'fastapi'],
    matchKeywords: ['python', '.py'],
  },
  {
    slug: 'go',
    displayName: 'Go',
    category: 'language',
    matchLanguages: ['Go'],
    matchTopics: ['golang', 'go'],
    matchKeywords: ['golang', '.go'],
  },
  {
    slug: 'rust',
    displayName: 'Rust',
    category: 'language',
    matchLanguages: ['Rust'],
    matchTopics: ['rust', 'rustlang', 'cargo'],
    matchKeywords: ['rust', '.rs', 'cargo'],
  },
  {
    slug: 'java',
    displayName: 'Java',
    category: 'language',
    matchLanguages: ['Java'],
    matchTopics: ['java', 'jvm', 'spring', 'spring-boot', 'maven', 'gradle'],
    matchKeywords: ['java', '.java', 'spring-boot'],
  },
  {
    slug: 'kotlin',
    displayName: 'Kotlin',
    category: 'language',
    matchLanguages: ['Kotlin'],
    matchTopics: ['kotlin', 'android-kotlin', 'kotlin-multiplatform', 'kmm', 'kmp'],
    matchKeywords: ['kotlin', '.kt', '.kts'],
  },
  {
    slug: 'swift',
    displayName: 'Swift',
    category: 'language',
    matchLanguages: ['Swift'],
    matchTopics: ['swift', 'swiftui', 'ios-swift', 'swift-package-manager'],
    matchKeywords: ['swift', '.swift', 'swiftui'],
  },
  {
    slug: 'cpp',
    displayName: 'C++',
    category: 'language',
    matchLanguages: ['C++'],
    matchTopics: ['cpp', 'cplusplus', 'c-plus-plus'],
    matchKeywords: ['c++', '.cpp', '.hpp', '.cc', '.cxx'],
  },
  {
    slug: 'c',
    displayName: 'C',
    category: 'language',
    matchLanguages: ['C'],
    matchTopics: ['c-programming', 'clang', 'c-language'],
    matchKeywords: ['.c', '.h'],
  },
  {
    slug: 'csharp',
    displayName: 'C#',
    category: 'language',
    matchLanguages: ['C#'],
    matchTopics: ['csharp', 'dotnet', 'dotnet-core', 'aspnet', 'unity'],
    matchKeywords: ['csharp', '.cs', 'dotnet', '.net'],
  },
  {
    slug: 'php',
    displayName: 'PHP',
    category: 'language',
    matchLanguages: ['PHP'],
    matchTopics: ['php', 'laravel', 'symfony', 'wordpress', 'composer'],
    matchKeywords: ['php', '.php', 'laravel', 'symfony'],
  },
  {
    slug: 'ruby',
    displayName: 'Ruby',
    category: 'language',
    matchLanguages: ['Ruby'],
    matchTopics: ['ruby', 'rails', 'ruby-on-rails', 'rubygems', 'sinatra'],
    matchKeywords: ['ruby', '.rb', 'rails'],
  },
  {
    slug: 'scala',
    displayName: 'Scala',
    category: 'language',
    matchLanguages: ['Scala'],
    matchTopics: ['scala', 'akka', 'play-framework', 'sbt'],
    matchKeywords: ['scala', '.scala'],
  },
  {
    slug: 'elixir',
    displayName: 'Elixir',
    category: 'language',
    matchLanguages: ['Elixir'],
    matchTopics: ['elixir', 'phoenix', 'erlang', 'otp'],
    matchKeywords: ['elixir', '.ex', '.exs', 'phoenix'],
  },
  {
    slug: 'haskell',
    displayName: 'Haskell',
    category: 'language',
    matchLanguages: ['Haskell'],
    matchTopics: ['haskell', 'functional-programming', 'ghc'],
    matchKeywords: ['haskell', '.hs'],
  },
  {
    slug: 'clojure',
    displayName: 'Clojure',
    category: 'language',
    matchLanguages: ['Clojure'],
    matchTopics: ['clojure', 'clojurescript', 'leiningen'],
    matchKeywords: ['clojure', '.clj', '.cljs'],
  },
  {
    slug: 'r',
    displayName: 'R',
    category: 'language',
    matchLanguages: ['R'],
    matchTopics: ['r', 'rstats', 'r-programming', 'tidyverse', 'ggplot2', 'shiny'],
    matchKeywords: ['.r', 'rstats'],
  },
  {
    slug: 'julia',
    displayName: 'Julia',
    category: 'language',
    matchLanguages: ['Julia'],
    matchTopics: ['julia', 'julialang', 'scientific-computing'],
    matchKeywords: ['julia', '.jl'],
  },
  {
    slug: 'dart',
    displayName: 'Dart',
    category: 'language',
    matchLanguages: ['Dart'],
    matchTopics: ['dart', 'flutter', 'dartlang'],
    matchKeywords: ['dart', '.dart'],
  },
  {
    slug: 'lua',
    displayName: 'Lua',
    category: 'language',
    matchLanguages: ['Lua'],
    matchTopics: ['lua', 'luajit', 'neovim', 'roblox'],
    matchKeywords: ['lua', '.lua'],
  },
  {
    slug: 'perl',
    displayName: 'Perl',
    category: 'language',
    matchLanguages: ['Perl'],
    matchTopics: ['perl', 'perl5', 'perl6', 'raku'],
    matchKeywords: ['perl', '.pl', '.pm'],
  },
  {
    slug: 'shell',
    displayName: 'Shell/Bash',
    category: 'language',
    matchLanguages: ['Shell', 'Bash'],
    matchTopics: ['shell', 'bash', 'zsh', 'shell-script', 'scripting'],
    matchKeywords: ['.sh', 'bash', 'shell'],
  },
  {
    slug: 'powershell',
    displayName: 'PowerShell',
    category: 'language',
    matchLanguages: ['PowerShell'],
    matchTopics: ['powershell', 'pwsh', 'windows-automation'],
    matchKeywords: ['powershell', '.ps1'],
  },
  {
    slug: 'objective-c',
    displayName: 'Objective-C',
    category: 'language',
    matchLanguages: ['Objective-C'],
    matchTopics: ['objective-c', 'objc', 'ios-objc'],
    matchKeywords: ['objective-c', '.m', '.mm'],
  },
  {
    slug: 'zig',
    displayName: 'Zig',
    category: 'language',
    matchLanguages: ['Zig'],
    matchTopics: ['zig', 'ziglang'],
    matchKeywords: ['zig', '.zig'],
  },
  {
    slug: 'nim',
    displayName: 'Nim',
    category: 'language',
    matchLanguages: ['Nim'],
    matchTopics: ['nim', 'nimlang'],
    matchKeywords: ['nim', '.nim'],
  },
  {
    slug: 'ocaml',
    displayName: 'OCaml',
    category: 'language',
    matchLanguages: ['OCaml'],
    matchTopics: ['ocaml', 'reason', 'reasonml'],
    matchKeywords: ['ocaml', '.ml', '.mli'],
  },
  {
    slug: 'fsharp',
    displayName: 'F#',
    category: 'language',
    matchLanguages: ['F#'],
    matchTopics: ['fsharp', 'dotnet-fsharp'],
    matchKeywords: ['fsharp', '.fs', '.fsx'],
  },
  {
    slug: 'solidity',
    displayName: 'Solidity',
    category: 'language',
    matchLanguages: ['Solidity'],
    matchTopics: ['solidity', 'smart-contracts', 'ethereum', 'evm'],
    matchKeywords: ['solidity', '.sol'],
  },
  {
    slug: 'vyper',
    displayName: 'Vyper',
    category: 'language',
    matchLanguages: ['Vyper'],
    matchTopics: ['vyper', 'ethereum-vyper'],
    matchKeywords: ['vyper', '.vy'],
  },
  {
    slug: 'move',
    displayName: 'Move',
    category: 'language',
    matchLanguages: ['Move'],
    matchTopics: ['move', 'aptos', 'sui', 'move-language'],
    matchKeywords: ['move', '.move'],
  },
  {
    slug: 'cairo',
    displayName: 'Cairo',
    category: 'language',
    matchLanguages: ['Cairo'],
    matchTopics: ['cairo', 'starknet', 'starkware'],
    matchKeywords: ['cairo', '.cairo'],
  },
  {
    slug: 'wasm',
    displayName: 'WebAssembly',
    category: 'language',
    matchLanguages: ['WebAssembly'],
    matchTopics: ['webassembly', 'wasm', 'wasi', 'emscripten'],
    matchKeywords: ['wasm', 'webassembly', '.wasm'],
  },
  {
    slug: 'cobol',
    displayName: 'COBOL',
    category: 'language',
    matchLanguages: ['COBOL'],
    matchTopics: ['cobol', 'mainframe'],
    matchKeywords: ['cobol', '.cob', '.cbl'],
  },
  {
    slug: 'fortran',
    displayName: 'Fortran',
    category: 'language',
    matchLanguages: ['Fortran'],
    matchTopics: ['fortran', 'scientific-computing', 'hpc'],
    matchKeywords: ['fortran', '.f90', '.f95'],
  },
  {
    slug: 'v',
    displayName: 'V',
    category: 'language',
    matchLanguages: ['V'],
    matchTopics: ['vlang', 'v-language'],
    matchKeywords: ['vlang', '.v'],
  },
  {
    slug: 'crystal',
    displayName: 'Crystal',
    category: 'language',
    matchLanguages: ['Crystal'],
    matchTopics: ['crystal', 'crystal-lang'],
    matchKeywords: ['crystal', '.cr'],
  },
  {
    slug: 'groovy',
    displayName: 'Groovy',
    category: 'language',
    matchLanguages: ['Groovy'],
    matchTopics: ['groovy', 'gradle', 'grails'],
    matchKeywords: ['groovy', '.groovy'],
  },
  {
    slug: 'erlang',
    displayName: 'Erlang',
    category: 'language',
    matchLanguages: ['Erlang'],
    matchTopics: ['erlang', 'otp', 'beam'],
    matchKeywords: ['erlang', '.erl'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRAMEWORKS - Frontend
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'react',
    displayName: 'React',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['react', 'reactjs', 'react-hooks', 'react-router', 'redux'],
    matchKeywords: ['react', 'jsx', 'tsx'],
  },
  {
    slug: 'nextjs',
    displayName: 'Next.js',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['nextjs', 'next-js', 'next', 'vercel'],
    matchKeywords: ['next.js', 'nextjs'],
  },
  {
    slug: 'vue',
    displayName: 'Vue',
    category: 'framework',
    matchLanguages: ['Vue'],
    matchTopics: ['vue', 'vuejs', 'vue3', 'vuex', 'pinia', 'nuxt'],
    matchKeywords: ['vue', '.vue', 'vuejs'],
  },
  {
    slug: 'nuxt',
    displayName: 'Nuxt',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['nuxt', 'nuxtjs', 'nuxt3'],
    matchKeywords: ['nuxt', 'nuxtjs'],
  },
  {
    slug: 'angular',
    displayName: 'Angular',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['angular', 'angularjs', 'angular2', 'ngrx', 'rxjs'],
    matchKeywords: ['angular'],
  },
  {
    slug: 'svelte',
    displayName: 'Svelte',
    category: 'framework',
    matchLanguages: ['Svelte'],
    matchTopics: ['svelte', 'sveltekit', 'svelte-kit'],
    matchKeywords: ['svelte', '.svelte'],
  },
  {
    slug: 'solid',
    displayName: 'SolidJS',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['solidjs', 'solid-js', 'solid-start'],
    matchKeywords: ['solidjs', 'solid-js'],
  },
  {
    slug: 'astro',
    displayName: 'Astro',
    category: 'framework',
    matchLanguages: ['Astro'],
    matchTopics: ['astro', 'astro-js', 'astrojs'],
    matchKeywords: ['astro', '.astro'],
  },
  {
    slug: 'remix',
    displayName: 'Remix',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['remix', 'remix-run'],
    matchKeywords: ['remix'],
  },
  {
    slug: 'qwik',
    displayName: 'Qwik',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['qwik', 'qwik-city'],
    matchKeywords: ['qwik'],
  },
  {
    slug: 'htmx',
    displayName: 'HTMX',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['htmx', 'hypermedia'],
    matchKeywords: ['htmx'],
  },
  {
    slug: 'alpine',
    displayName: 'Alpine.js',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['alpinejs', 'alpine-js'],
    matchKeywords: ['alpinejs', 'alpine.js'],
  },
  {
    slug: 'ember',
    displayName: 'Ember.js',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['ember', 'emberjs', 'ember-cli'],
    matchKeywords: ['ember', 'emberjs'],
  },
  {
    slug: 'preact',
    displayName: 'Preact',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['preact', 'preactjs'],
    matchKeywords: ['preact'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRAMEWORKS - Backend
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'django',
    displayName: 'Django',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['django', 'django-rest-framework', 'drf', 'django-ninja'],
    matchKeywords: ['django'],
  },
  {
    slug: 'fastapi',
    displayName: 'FastAPI',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['fastapi', 'starlette'],
    matchKeywords: ['fastapi'],
  },
  {
    slug: 'flask',
    displayName: 'Flask',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['flask', 'flask-restful'],
    matchKeywords: ['flask'],
  },
  {
    slug: 'express',
    displayName: 'Express.js',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['express', 'expressjs', 'express-js'],
    matchKeywords: ['express', 'expressjs'],
  },
  {
    slug: 'nestjs',
    displayName: 'NestJS',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['nestjs', 'nest-js'],
    matchKeywords: ['nestjs', 'nest.js'],
  },
  {
    slug: 'fastify',
    displayName: 'Fastify',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['fastify'],
    matchKeywords: ['fastify'],
  },
  {
    slug: 'hono',
    displayName: 'Hono',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['hono', 'honojs'],
    matchKeywords: ['hono'],
  },
  {
    slug: 'spring',
    displayName: 'Spring',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['spring', 'spring-boot', 'spring-framework', 'spring-cloud'],
    matchKeywords: ['spring', 'spring-boot'],
  },
  {
    slug: 'rails',
    displayName: 'Ruby on Rails',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['rails', 'ruby-on-rails', 'rubyonrails'],
    matchKeywords: ['rails', 'rubyonrails'],
  },
  {
    slug: 'laravel',
    displayName: 'Laravel',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['laravel', 'laravel-framework', 'lumen'],
    matchKeywords: ['laravel'],
  },
  {
    slug: 'symfony',
    displayName: 'Symfony',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['symfony', 'symfony-framework'],
    matchKeywords: ['symfony'],
  },
  {
    slug: 'gin',
    displayName: 'Gin',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['gin', 'gin-gonic'],
    matchKeywords: ['gin-gonic', 'gin'],
  },
  {
    slug: 'fiber',
    displayName: 'Fiber',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['fiber', 'gofiber'],
    matchKeywords: ['fiber', 'gofiber'],
  },
  {
    slug: 'echo',
    displayName: 'Echo',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['echo', 'labstack-echo'],
    matchKeywords: ['echo', 'labstack'],
  },
  {
    slug: 'actix',
    displayName: 'Actix',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['actix', 'actix-web'],
    matchKeywords: ['actix', 'actix-web'],
  },
  {
    slug: 'axum',
    displayName: 'Axum',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['axum', 'tokio'],
    matchKeywords: ['axum'],
  },
  {
    slug: 'rocket',
    displayName: 'Rocket',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['rocket', 'rocket-rs'],
    matchKeywords: ['rocket'],
  },
  {
    slug: 'phoenix',
    displayName: 'Phoenix',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['phoenix', 'phoenix-framework', 'phoenix-liveview'],
    matchKeywords: ['phoenix'],
  },
  {
    slug: 'aspnet',
    displayName: 'ASP.NET',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['aspnet', 'aspnetcore', 'asp-net-core', 'blazor'],
    matchKeywords: ['aspnet', 'asp.net', 'blazor'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRAMEWORKS - Mobile
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'react-native',
    displayName: 'React Native',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['react-native', 'reactnative', 'expo'],
    matchKeywords: ['react-native', 'expo'],
  },
  {
    slug: 'flutter',
    displayName: 'Flutter',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['flutter', 'flutter-apps', 'flutterdev'],
    matchKeywords: ['flutter'],
  },
  {
    slug: 'ionic',
    displayName: 'Ionic',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['ionic', 'ionic-framework', 'capacitor'],
    matchKeywords: ['ionic', 'capacitor'],
  },
  {
    slug: 'swiftui',
    displayName: 'SwiftUI',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['swiftui', 'swift-ui'],
    matchKeywords: ['swiftui'],
  },
  {
    slug: 'jetpack-compose',
    displayName: 'Jetpack Compose',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['jetpack-compose', 'compose', 'android-compose'],
    matchKeywords: ['jetpack-compose', 'compose'],
  },
  {
    slug: 'tauri',
    displayName: 'Tauri',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['tauri', 'tauri-apps'],
    matchKeywords: ['tauri'],
  },
  {
    slug: 'electron',
    displayName: 'Electron',
    category: 'framework',
    matchLanguages: [],
    matchTopics: ['electron', 'electronjs', 'electron-app'],
    matchKeywords: ['electron'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLATFORMS - Cloud & Infrastructure
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'docker',
    displayName: 'Docker',
    category: 'platform',
    matchLanguages: ['Dockerfile'],
    matchTopics: ['docker', 'containers', 'containerization', 'docker-compose'],
    matchKeywords: ['docker', 'dockerfile', 'docker-compose'],
  },
  {
    slug: 'kubernetes',
    displayName: 'Kubernetes',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['kubernetes', 'k8s', 'helm', 'kubectl', 'minikube', 'kind'],
    matchKeywords: ['kubernetes', 'k8s', 'kubectl', 'helm'],
  },
  {
    slug: 'aws',
    displayName: 'AWS',
    category: 'platform',
    matchLanguages: [],
    matchTopics: [
      'aws',
      'amazon-web-services',
      'lambda',
      's3',
      'ec2',
      'dynamodb',
      'cloudformation',
      'cdk',
      'sagemaker',
    ],
    matchKeywords: ['aws', 'amazon', 'lambda', 'cloudformation', 'sagemaker'],
  },
  {
    slug: 'gcp',
    displayName: 'Google Cloud',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['gcp', 'google-cloud', 'firebase', 'bigquery', 'cloud-run', 'cloud-functions'],
    matchKeywords: ['gcp', 'google-cloud', 'firebase', 'bigquery'],
  },
  {
    slug: 'azure',
    displayName: 'Azure',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['azure', 'microsoft-azure', 'azure-functions', 'azure-devops'],
    matchKeywords: ['azure'],
  },
  {
    slug: 'vercel',
    displayName: 'Vercel',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['vercel', 'zeit'],
    matchKeywords: ['vercel'],
  },
  {
    slug: 'netlify',
    displayName: 'Netlify',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['netlify', 'netlify-cms'],
    matchKeywords: ['netlify'],
  },
  {
    slug: 'cloudflare',
    displayName: 'Cloudflare',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['cloudflare', 'cloudflare-workers', 'cloudflare-pages', 'wrangler'],
    matchKeywords: ['cloudflare', 'workers'],
  },
  {
    slug: 'supabase',
    displayName: 'Supabase',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['supabase'],
    matchKeywords: ['supabase'],
  },
  {
    slug: 'planetscale',
    displayName: 'PlanetScale',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['planetscale', 'vitess'],
    matchKeywords: ['planetscale'],
  },
  {
    slug: 'digitalocean',
    displayName: 'DigitalOcean',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['digitalocean', 'do'],
    matchKeywords: ['digitalocean'],
  },
  {
    slug: 'heroku',
    displayName: 'Heroku',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['heroku'],
    matchKeywords: ['heroku'],
  },
  {
    slug: 'railway',
    displayName: 'Railway',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['railway', 'railway-app'],
    matchKeywords: ['railway'],
  },
  {
    slug: 'fly',
    displayName: 'Fly.io',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['fly', 'flyio', 'fly-io'],
    matchKeywords: ['fly.io', 'flyctl'],
  },
  {
    slug: 'terraform',
    displayName: 'Terraform',
    category: 'platform',
    matchLanguages: ['HCL'],
    matchTopics: ['terraform', 'infrastructure-as-code', 'iac', 'hashicorp'],
    matchKeywords: ['terraform', '.tf'],
  },
  {
    slug: 'pulumi',
    displayName: 'Pulumi',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['pulumi', 'infrastructure-as-code'],
    matchKeywords: ['pulumi'],
  },
  {
    slug: 'ansible',
    displayName: 'Ansible',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['ansible', 'ansible-playbook', 'ansible-role'],
    matchKeywords: ['ansible'],
  },
  {
    slug: 'openshift',
    displayName: 'OpenShift',
    category: 'platform',
    matchLanguages: [],
    matchTopics: ['openshift', 'openshift-container-platform'],
    matchKeywords: ['openshift'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Blockchain / Web3
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'blockchain',
    displayName: 'Blockchain',
    category: 'domain',
    matchLanguages: ['Solidity', 'Vyper', 'Move', 'Cairo'],
    matchTopics: ['blockchain', 'distributed-ledger', 'consensus'],
    matchKeywords: ['blockchain'],
  },
  {
    slug: 'web3',
    displayName: 'Web3',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['web3', 'web3js', 'ethersjs', 'wagmi', 'viem', 'rainbowkit'],
    matchKeywords: ['web3', 'dapp', 'dapps'],
  },
  {
    slug: 'ethereum',
    displayName: 'Ethereum',
    category: 'domain',
    matchLanguages: ['Solidity'],
    matchTopics: ['ethereum', 'eth', 'evm', 'erc20', 'erc721', 'erc1155', 'eip'],
    matchKeywords: ['ethereum', 'eth', 'evm'],
  },
  {
    slug: 'defi',
    displayName: 'DeFi',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'defi',
      'decentralized-finance',
      'dex',
      'amm',
      'yield-farming',
      'liquidity',
      'uniswap',
      'aave',
      'compound',
    ],
    matchKeywords: ['defi', 'dex', 'amm', 'swap'],
  },
  {
    slug: 'nft',
    displayName: 'NFT',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['nft', 'nfts', 'non-fungible-token', 'erc721', 'erc1155', 'opensea'],
    matchKeywords: ['nft', 'non-fungible'],
  },
  {
    slug: 'smart-contracts',
    displayName: 'Smart Contracts',
    category: 'domain',
    matchLanguages: ['Solidity', 'Vyper'],
    matchTopics: ['smart-contracts', 'smartcontracts', 'hardhat', 'foundry', 'truffle', 'remix'],
    matchKeywords: ['smart-contract', 'hardhat', 'foundry'],
  },
  {
    slug: 'bitcoin',
    displayName: 'Bitcoin',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['bitcoin', 'btc', 'lightning-network', 'ordinals', 'brc20'],
    matchKeywords: ['bitcoin', 'btc', 'lightning'],
  },
  {
    slug: 'solana',
    displayName: 'Solana',
    category: 'domain',
    matchLanguages: ['Rust'],
    matchTopics: ['solana', 'sol', 'anchor', 'solana-program'],
    matchKeywords: ['solana', 'anchor'],
  },
  {
    slug: 'polkadot',
    displayName: 'Polkadot',
    category: 'domain',
    matchLanguages: ['Rust'],
    matchTopics: ['polkadot', 'substrate', 'parachain', 'kusama'],
    matchKeywords: ['polkadot', 'substrate'],
  },
  {
    slug: 'cosmos',
    displayName: 'Cosmos',
    category: 'domain',
    matchLanguages: ['Go'],
    matchTopics: ['cosmos', 'cosmos-sdk', 'tendermint', 'ibc'],
    matchKeywords: ['cosmos', 'tendermint'],
  },
  {
    slug: 'avalanche',
    displayName: 'Avalanche',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['avalanche', 'avax', 'subnet'],
    matchKeywords: ['avalanche', 'avax'],
  },
  {
    slug: 'polygon',
    displayName: 'Polygon',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['polygon', 'matic', 'polygon-network'],
    matchKeywords: ['polygon', 'matic'],
  },
  {
    slug: 'arbitrum',
    displayName: 'Arbitrum',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['arbitrum', 'layer2', 'l2'],
    matchKeywords: ['arbitrum'],
  },
  {
    slug: 'optimism',
    displayName: 'Optimism',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['optimism', 'op-stack', 'layer2'],
    matchKeywords: ['optimism', 'op-stack'],
  },
  {
    slug: 'zk',
    displayName: 'Zero Knowledge',
    category: 'domain',
    matchLanguages: ['Circom', 'Cairo'],
    matchTopics: [
      'zero-knowledge',
      'zk',
      'zkp',
      'zk-snark',
      'zk-stark',
      'zkrollup',
      'circom',
      'noir',
    ],
    matchKeywords: ['zero-knowledge', 'zk-snark', 'zk-stark', 'zkrollup'],
  },
  {
    slug: 'dao',
    displayName: 'DAO',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'dao',
      'decentralized-autonomous-organization',
      'governance',
      'aragon',
      'snapshot',
    ],
    matchKeywords: ['dao', 'governance'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - AI / ML
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'ai',
    displayName: 'AI / ML',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['artificial-intelligence', 'machine-learning', 'deep-learning', 'ai', 'ml'],
    matchKeywords: ['artificial-intelligence', 'machine-learning', 'deep-learning'],
  },
  {
    slug: 'llm',
    displayName: 'LLM',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'llm',
      'large-language-model',
      'gpt',
      'chatgpt',
      'openai',
      'claude',
      'llama',
      'mistral',
      'gemini',
    ],
    matchKeywords: ['llm', 'gpt', 'chatgpt', 'openai', 'langchain', 'llama'],
  },
  {
    slug: 'agents',
    displayName: 'AI Agents',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'ai-agents',
      'autonomous-agents',
      'agent',
      'autogpt',
      'langchain',
      'crewai',
      'autogen',
    ],
    matchKeywords: ['ai-agent', 'autonomous-agent', 'autogpt', 'crewai'],
  },
  {
    slug: 'nlp',
    displayName: 'NLP',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'nlp',
      'natural-language-processing',
      'text-mining',
      'sentiment-analysis',
      'ner',
      'transformers',
    ],
    matchKeywords: ['nlp', 'natural-language'],
  },
  {
    slug: 'computer-vision',
    displayName: 'Computer Vision',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'computer-vision',
      'cv',
      'image-processing',
      'object-detection',
      'image-classification',
      'yolo',
      'opencv',
    ],
    matchKeywords: ['computer-vision', 'opencv', 'yolo'],
  },
  {
    slug: 'generative-ai',
    displayName: 'Generative AI',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'generative-ai',
      'stable-diffusion',
      'midjourney',
      'dalle',
      'diffusion',
      'text-to-image',
      'image-generation',
    ],
    matchKeywords: ['generative-ai', 'stable-diffusion', 'diffusion'],
  },
  {
    slug: 'rag',
    displayName: 'RAG',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'rag',
      'retrieval-augmented-generation',
      'vector-database',
      'embeddings',
      'semantic-search',
    ],
    matchKeywords: ['rag', 'retrieval-augmented', 'embeddings'],
  },
  {
    slug: 'mlops',
    displayName: 'MLOps',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['mlops', 'ml-ops', 'mlflow', 'kubeflow', 'model-serving', 'model-deployment'],
    matchKeywords: ['mlops', 'mlflow', 'kubeflow'],
  },
  {
    slug: 'tensorflow',
    displayName: 'TensorFlow',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['tensorflow', 'tf', 'keras', 'tf-keras'],
    matchKeywords: ['tensorflow', 'keras'],
  },
  {
    slug: 'pytorch',
    displayName: 'PyTorch',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['pytorch', 'torch', 'torchvision'],
    matchKeywords: ['pytorch', 'torch'],
  },
  {
    slug: 'huggingface',
    displayName: 'Hugging Face',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['huggingface', 'transformers', 'diffusers', 'datasets'],
    matchKeywords: ['huggingface', 'hugging-face'],
  },
  {
    slug: 'langchain',
    displayName: 'LangChain',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['langchain', 'langgraph', 'langsmith'],
    matchKeywords: ['langchain', 'langgraph'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Security
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'security',
    displayName: 'Security',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['security', 'cybersecurity', 'infosec', 'appsec', 'application-security'],
    matchKeywords: ['security', 'cybersecurity'],
  },
  {
    slug: 'pentesting',
    displayName: 'Pentesting',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['penetration-testing', 'pentesting', 'ethical-hacking', 'bug-bounty', 'ctf'],
    matchKeywords: ['pentesting', 'pentest', 'ethical-hacking'],
  },
  {
    slug: 'cryptography',
    displayName: 'Cryptography',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['cryptography', 'encryption', 'crypto', 'hashing', 'ssl', 'tls'],
    matchKeywords: ['cryptography', 'encryption'],
  },
  {
    slug: 'devsecops',
    displayName: 'DevSecOps',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['devsecops', 'security-automation', 'sast', 'dast', 'snyk', 'trivy'],
    matchKeywords: ['devsecops', 'security-automation'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - DevOps & Infrastructure
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'devops',
    displayName: 'DevOps',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['devops', 'ci-cd', 'continuous-integration', 'continuous-deployment', 'gitops'],
    matchKeywords: ['devops', 'ci/cd', 'cicd'],
  },
  {
    slug: 'sre',
    displayName: 'SRE',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['sre', 'site-reliability-engineering', 'observability', 'monitoring', 'alerting'],
    matchKeywords: ['sre', 'site-reliability'],
  },
  {
    slug: 'platform-engineering',
    displayName: 'Platform Engineering',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['platform-engineering', 'internal-developer-platform', 'idp', 'backstage'],
    matchKeywords: ['platform-engineering', 'backstage'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Data
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'data-engineering',
    displayName: 'Data Engineering',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['data-engineering', 'etl', 'data-pipeline', 'data-warehouse', 'data-lake'],
    matchKeywords: ['data-engineering', 'etl', 'data-pipeline'],
  },
  {
    slug: 'data-science',
    displayName: 'Data Science',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['data-science', 'datascience', 'data-analysis', 'statistics', 'pandas', 'numpy'],
    matchKeywords: ['data-science', 'datascience'],
  },
  {
    slug: 'analytics',
    displayName: 'Analytics',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'analytics',
      'business-intelligence',
      'bi',
      'data-visualization',
      'tableau',
      'looker',
      'metabase',
    ],
    matchKeywords: ['analytics', 'business-intelligence'],
  },
  {
    slug: 'streaming',
    displayName: 'Data Streaming',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'kafka',
      'apache-kafka',
      'streaming',
      'stream-processing',
      'flink',
      'spark-streaming',
      'pulsar',
    ],
    matchKeywords: ['kafka', 'streaming', 'flink'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Mobile
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'ios',
    displayName: 'iOS',
    category: 'domain',
    matchLanguages: ['Swift', 'Objective-C'],
    matchTopics: ['ios', 'ios-app', 'iphone', 'ipad', 'apple', 'uikit', 'swiftui'],
    matchKeywords: ['ios', 'iphone', 'ipad'],
  },
  {
    slug: 'android',
    displayName: 'Android',
    category: 'domain',
    matchLanguages: ['Kotlin', 'Java'],
    matchTopics: ['android', 'android-app', 'android-development', 'jetpack'],
    matchKeywords: ['android'],
  },
  {
    slug: 'mobile',
    displayName: 'Mobile',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['mobile', 'mobile-app', 'mobile-development', 'cross-platform'],
    matchKeywords: ['mobile'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Game Development
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'gamedev',
    displayName: 'Game Dev',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['gamedev', 'game-development', 'game-dev', 'gaming', 'game-engine', 'game'],
    matchKeywords: ['gamedev', 'game-dev'],
  },
  {
    slug: 'unity',
    displayName: 'Unity',
    category: 'domain',
    matchLanguages: ['C#'],
    matchTopics: ['unity', 'unity3d', 'unity-game-development', 'unityscript'],
    matchKeywords: ['unity', 'unity3d'],
  },
  {
    slug: 'unreal',
    displayName: 'Unreal Engine',
    category: 'domain',
    matchLanguages: ['C++'],
    matchTopics: ['unreal', 'unreal-engine', 'ue4', 'ue5', 'blueprints'],
    matchKeywords: ['unreal', 'unreal-engine'],
  },
  {
    slug: 'godot',
    displayName: 'Godot',
    category: 'domain',
    matchLanguages: ['GDScript'],
    matchTopics: ['godot', 'godot-engine', 'gdscript'],
    matchKeywords: ['godot'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAINS - Other
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'frontend',
    displayName: 'Frontend',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['frontend', 'front-end', 'ui', 'ux', 'web', 'css', 'html', 'responsive'],
    matchKeywords: ['frontend', 'front-end'],
  },
  {
    slug: 'backend',
    displayName: 'Backend',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['backend', 'back-end', 'api', 'server', 'rest-api', 'microservices'],
    matchKeywords: ['backend', 'back-end', 'server'],
  },
  {
    slug: 'fullstack',
    displayName: 'Full Stack',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['fullstack', 'full-stack', 'full-stack-development'],
    matchKeywords: ['fullstack', 'full-stack'],
  },
  {
    slug: 'embedded',
    displayName: 'Embedded',
    category: 'domain',
    matchLanguages: ['C', 'C++', 'Rust'],
    matchTopics: ['embedded', 'embedded-systems', 'firmware', 'microcontroller', 'rtos', 'arm'],
    matchKeywords: ['embedded', 'firmware', 'microcontroller'],
  },
  {
    slug: 'iot',
    displayName: 'IoT',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'iot',
      'internet-of-things',
      'mqtt',
      'esp32',
      'arduino',
      'raspberry-pi',
      'home-automation',
    ],
    matchKeywords: ['iot', 'internet-of-things', 'mqtt'],
  },
  {
    slug: 'robotics',
    displayName: 'Robotics',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['robotics', 'ros', 'ros2', 'robot', 'autonomous', 'slam'],
    matchKeywords: ['robotics', 'ros', 'robot'],
  },
  {
    slug: 'ar-vr',
    displayName: 'AR/VR',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'ar',
      'vr',
      'augmented-reality',
      'virtual-reality',
      'xr',
      'mixed-reality',
      'metaverse',
      'webxr',
    ],
    matchKeywords: ['augmented-reality', 'virtual-reality', 'ar', 'vr'],
  },
  {
    slug: 'graphics',
    displayName: '3D Graphics',
    category: 'domain',
    matchLanguages: ['GLSL', 'HLSL'],
    matchTopics: ['graphics', '3d', 'opengl', 'vulkan', 'webgl', 'threejs', 'shader', 'rendering'],
    matchKeywords: ['opengl', 'vulkan', 'webgl', 'threejs'],
  },
  {
    slug: 'audio',
    displayName: 'Audio',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['audio', 'music', 'dsp', 'audio-processing', 'web-audio', 'synthesizer'],
    matchKeywords: ['audio', 'dsp', 'synthesizer'],
  },
  {
    slug: 'video',
    displayName: 'Video',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['video', 'video-processing', 'ffmpeg', 'streaming', 'video-editing', 'codec'],
    matchKeywords: ['video', 'ffmpeg', 'codec'],
  },
  {
    slug: 'cli',
    displayName: 'CLI',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['cli', 'command-line', 'terminal', 'shell', 'console'],
    matchKeywords: ['cli', 'command-line'],
  },
  {
    slug: 'api-design',
    displayName: 'API Design',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['api', 'rest', 'restful', 'openapi', 'swagger', 'api-design', 'grpc'],
    matchKeywords: ['api', 'rest', 'openapi', 'swagger'],
  },
  {
    slug: 'testing',
    displayName: 'Testing',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'testing',
      'unit-testing',
      'e2e',
      'integration-testing',
      'jest',
      'cypress',
      'playwright',
      'pytest',
    ],
    matchKeywords: ['testing', 'test', 'jest', 'cypress', 'playwright'],
  },
  {
    slug: 'open-source',
    displayName: 'Open Source',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['open-source', 'opensource', 'oss', 'hacktoberfest', 'contributing'],
    matchKeywords: ['open-source', 'opensource'],
  },
  {
    slug: 'accessibility',
    displayName: 'Accessibility',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['accessibility', 'a11y', 'wcag', 'aria', 'screen-reader'],
    matchKeywords: ['accessibility', 'a11y'],
  },
  {
    slug: 'performance',
    displayName: 'Performance',
    category: 'domain',
    matchLanguages: [],
    matchTopics: [
      'performance',
      'optimization',
      'web-performance',
      'lighthouse',
      'core-web-vitals',
    ],
    matchKeywords: ['performance', 'optimization'],
  },
  {
    slug: 'serverless',
    displayName: 'Serverless',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['serverless', 'faas', 'lambda', 'cloud-functions', 'serverless-framework'],
    matchKeywords: ['serverless', 'faas'],
  },
  {
    slug: 'microservices',
    displayName: 'Microservices',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['microservices', 'microservice', 'service-mesh', 'istio', 'linkerd'],
    matchKeywords: ['microservices', 'microservice'],
  },
  {
    slug: 'monorepo',
    displayName: 'Monorepo',
    category: 'domain',
    matchLanguages: [],
    matchTopics: ['monorepo', 'turborepo', 'nx', 'lerna', 'pnpm-workspace'],
    matchKeywords: ['monorepo', 'turborepo', 'nx'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - Databases
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'graphql',
    displayName: 'GraphQL',
    category: 'tool',
    matchLanguages: ['GraphQL'],
    matchTopics: ['graphql', 'apollo', 'graphql-api', 'hasura', 'relay'],
    matchKeywords: ['graphql', 'apollo'],
  },
  {
    slug: 'postgresql',
    displayName: 'PostgreSQL',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['postgresql', 'postgres', 'sql', 'psql', 'pg'],
    matchKeywords: ['postgresql', 'postgres', 'psql'],
  },
  {
    slug: 'mysql',
    displayName: 'MySQL',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['mysql', 'mariadb'],
    matchKeywords: ['mysql', 'mariadb'],
  },
  {
    slug: 'mongodb',
    displayName: 'MongoDB',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['mongodb', 'mongoose', 'nosql', 'mongo'],
    matchKeywords: ['mongodb', 'mongoose', 'mongo'],
  },
  {
    slug: 'redis',
    displayName: 'Redis',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['redis', 'caching', 'in-memory'],
    matchKeywords: ['redis'],
  },
  {
    slug: 'elasticsearch',
    displayName: 'Elasticsearch',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['elasticsearch', 'elastic', 'elk', 'opensearch'],
    matchKeywords: ['elasticsearch', 'elastic'],
  },
  {
    slug: 'cassandra',
    displayName: 'Cassandra',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['cassandra', 'apache-cassandra', 'scylla'],
    matchKeywords: ['cassandra', 'scylla'],
  },
  {
    slug: 'sqlite',
    displayName: 'SQLite',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['sqlite', 'sqlite3'],
    matchKeywords: ['sqlite'],
  },
  {
    slug: 'dynamodb',
    displayName: 'DynamoDB',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['dynamodb', 'dynamo'],
    matchKeywords: ['dynamodb'],
  },
  {
    slug: 'neo4j',
    displayName: 'Neo4j',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['neo4j', 'graph-database', 'cypher'],
    matchKeywords: ['neo4j', 'graph-database'],
  },
  {
    slug: 'clickhouse',
    displayName: 'ClickHouse',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['clickhouse', 'olap', 'analytics-database'],
    matchKeywords: ['clickhouse'],
  },
  {
    slug: 'drizzle',
    displayName: 'Drizzle',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['drizzle', 'drizzle-orm'],
    matchKeywords: ['drizzle'],
  },
  {
    slug: 'prisma',
    displayName: 'Prisma',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['prisma', 'prisma-orm'],
    matchKeywords: ['prisma'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - Message Queues & Streaming
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'kafka',
    displayName: 'Kafka',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['kafka', 'apache-kafka', 'confluent'],
    matchKeywords: ['kafka'],
  },
  {
    slug: 'rabbitmq',
    displayName: 'RabbitMQ',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['rabbitmq', 'amqp', 'message-queue'],
    matchKeywords: ['rabbitmq', 'amqp'],
  },
  {
    slug: 'nats',
    displayName: 'NATS',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['nats', 'nats-io', 'jetstream'],
    matchKeywords: ['nats'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - CI/CD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'github-actions',
    displayName: 'GitHub Actions',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['github-actions', 'github-action', 'actions'],
    matchKeywords: ['github-actions'],
  },
  {
    slug: 'gitlab-ci',
    displayName: 'GitLab CI',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['gitlab-ci', 'gitlab', 'gitlab-runner'],
    matchKeywords: ['gitlab-ci', 'gitlab'],
  },
  {
    slug: 'jenkins',
    displayName: 'Jenkins',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['jenkins', 'jenkinsfile', 'jenkins-pipeline'],
    matchKeywords: ['jenkins'],
  },
  {
    slug: 'circleci',
    displayName: 'CircleCI',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['circleci', 'circle-ci'],
    matchKeywords: ['circleci'],
  },
  {
    slug: 'argocd',
    displayName: 'ArgoCD',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['argocd', 'argo-cd', 'gitops'],
    matchKeywords: ['argocd', 'argo-cd'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - Monitoring & Observability
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'prometheus',
    displayName: 'Prometheus',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['prometheus', 'prometheus-monitoring'],
    matchKeywords: ['prometheus'],
  },
  {
    slug: 'grafana',
    displayName: 'Grafana',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['grafana', 'grafana-dashboard'],
    matchKeywords: ['grafana'],
  },
  {
    slug: 'datadog',
    displayName: 'Datadog',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['datadog', 'dd'],
    matchKeywords: ['datadog'],
  },
  {
    slug: 'opentelemetry',
    displayName: 'OpenTelemetry',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['opentelemetry', 'otel', 'tracing', 'observability'],
    matchKeywords: ['opentelemetry', 'otel'],
  },
  {
    slug: 'sentry',
    displayName: 'Sentry',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['sentry', 'error-tracking'],
    matchKeywords: ['sentry'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - Data Processing
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'spark',
    displayName: 'Apache Spark',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['spark', 'apache-spark', 'pyspark'],
    matchKeywords: ['spark', 'pyspark'],
  },
  {
    slug: 'airflow',
    displayName: 'Apache Airflow',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['airflow', 'apache-airflow', 'dag'],
    matchKeywords: ['airflow'],
  },
  {
    slug: 'dbt',
    displayName: 'dbt',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['dbt', 'data-build-tool', 'dbt-core'],
    matchKeywords: ['dbt'],
  },
  {
    slug: 'flink',
    displayName: 'Apache Flink',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['flink', 'apache-flink'],
    matchKeywords: ['flink'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS - Other
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'git',
    displayName: 'Git',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['git', 'version-control', 'github', 'gitlab', 'bitbucket'],
    matchKeywords: ['git'],
  },
  {
    slug: 'nginx',
    displayName: 'Nginx',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['nginx', 'reverse-proxy', 'load-balancer'],
    matchKeywords: ['nginx'],
  },
  {
    slug: 'vscode',
    displayName: 'VS Code',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['vscode', 'visual-studio-code', 'vscode-extension'],
    matchKeywords: ['vscode', 'visual-studio-code'],
  },
  {
    slug: 'neovim',
    displayName: 'Neovim',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['neovim', 'nvim', 'vim', 'neovim-plugin'],
    matchKeywords: ['neovim', 'nvim'],
  },
  {
    slug: 'linux',
    displayName: 'Linux',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['linux', 'unix', 'debian', 'ubuntu', 'fedora', 'arch-linux'],
    matchKeywords: ['linux', 'ubuntu', 'debian'],
  },
  {
    slug: 'webpack',
    displayName: 'Webpack',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['webpack', 'bundler'],
    matchKeywords: ['webpack'],
  },
  {
    slug: 'vite',
    displayName: 'Vite',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['vite', 'vitejs'],
    matchKeywords: ['vite'],
  },
  {
    slug: 'esbuild',
    displayName: 'esbuild',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['esbuild'],
    matchKeywords: ['esbuild'],
  },
  {
    slug: 'tailwind',
    displayName: 'Tailwind CSS',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['tailwindcss', 'tailwind', 'tailwind-css'],
    matchKeywords: ['tailwind', 'tailwindcss'],
  },
  {
    slug: 'sass',
    displayName: 'Sass/SCSS',
    category: 'tool',
    matchLanguages: ['SCSS', 'Sass'],
    matchTopics: ['sass', 'scss'],
    matchKeywords: ['sass', 'scss'],
  },
  {
    slug: 'storybook',
    displayName: 'Storybook',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['storybook', 'component-library'],
    matchKeywords: ['storybook'],
  },
  {
    slug: 'figma',
    displayName: 'Figma',
    category: 'tool',
    matchLanguages: [],
    matchTopics: ['figma', 'figma-plugin', 'design-system'],
    matchKeywords: ['figma'],
  },
];
